### ISSUE TITLE
Doesn't list all my programs

### ISSUE THREAD

**Issue by frestalink** [guilryder/clavier-plus#34] opened 2023-01-11 00:26 UTC
Add 'Program' does not list all the programs I have installed (Windows 10 22H2), there is no option to show more programs as in the add 'App' function that has an arrow at the bottom to scroll more applications.

**Comment by guilryder** [comment] 2023-01-12 09:16
Do you mean that the _Program_ menu or one of its sub-menus is too tall to fit in the screen?

If yes, it's a bug caused by recent Windows versions using a larger menu height. I will fix it.

If no, the _Program_ menu isn't supposed to list all installed programs, but only the same entries as the Windows Start menu. If a program you want isn't in the list, create a shortcut for it manually via _Add Program_.

**Comment by frestalink** [comment] 2023-01-12 16:05
Yes the Program menu and sub-menus.

To create I used "Ctrl + Alt + ←" to rotate the screen.
Then "Ctrl + Alt + ↑" to return to normal.

Thanks

**Comment by guilryder** [comment] 2023-01-14 23:28
Fixed in https://github.com/guilryder/clavier-plus/commit/28730fce83b2eff932cff720211072e08a303e33

**Closed by guilryder** 2023-01-14 23:28 UTC
Labels: bug
