### ISSUE TITLE
Feature Request: Option to restore window if process already exists

### ISSUE THREAD

**Issue by rp1231** [guilryder/clavier-plus#23] opened 2022-03-13 21:39 UTC
Hi,

It would be great if there was an option to restore or bring the window to the front if the program shortcut is pressed.
Sometimes you just want to bring up the program that you have already launched.
Hope you can incorporate this feature.

Thanks

**Comment by guilryder** [comment] 2022-03-13 22:57
Duplicate of https://github.com/guilryder/clavier-plus/issues/16. Already implemented, see `[{FocusOrLaunch}]`.

**Closed by guilryder** 2022-03-13 22:57 UTC
Labels: duplicate

**Comment by rp1231** [comment] 2022-03-13 23:47
Thanks,
This works perfectly!
