### ISSUE TITLE
[Feature Request] add option to put focus on an app when already running

### ISSUE THREAD

**Issue by schmurtzm** [guilryder/clavier-plus#16] opened 2022-01-12 18:13 UTC
Hi,

A checkbox "Put focus if already running" could be very useful.

Most of the users shortcuts are probably using clavier+ to run programs, so when you launch a shortcut of an app which is already running there are 2 possible behaviors : 
- if the app allow only one instance -> the app will come in front with focus
- if the app allow multiple instance -> the app will open a new instance, it means a new windows which sometime is not the desired behavior .

Real-life example : 
My shortcut to run notepad++ is perfect , it runs it and if it is already running the app comes in front with focus. 
On the other hand my OneNote shortcut will launch one new window of OneNote each time (and I can't force only one instance).

Thank you.

**Comment by guilryder** [comment] 2022-01-14 06:47
I don't think it's possible to implement this in a general manner. As far as I know there is no standard mechanism to figure out if a given window is the already-running manifestation of a given command-line.

I can think of heuristics that work sometimes but not always. For instance, a shortcut that opens file X with Notepad++ should execute the command-line even if Notepad++ is already launched but for a different file Y.

Clavier+ could instead leave it up to the user to identify the window to activate, for instance with a command for "give the focus to the first window named X if one exists, else run command-line Y" i.e. a conditional combination of `[{Focus,0,<window name>}]` and `[[<command line>]]`. In the mean time you can achieve the same effect with a script and configure Clavier+ to associate a keyboard shortcut to that script (for instance with `AppActivate` and `Execute` in VBScript).

**Comment by guilryder** [comment] 2022-01-16 23:47
Added a `[{FocusOrLaunch,<window name>,<delay>,<command>}]` command to the beta version: http://utilfr42.free.fr/dn/beta/Clavier.exe

If `[{FocusOrLaunch}]` finds the window, it behaves like `[{Focus,0,<window name>}]` (no delay). Else, it behaves like `[[<command>]][{Focus,<delay>}]`

I still need to support comma escaping, test thoroughly, and update the documentation.

**Comment by schmurtzm** [comment] 2022-01-17 03:46
I like it so much , it is very fast ! Really thank you for the awesome support you make on your app ! 
Some remarks about the beta : 

- Little bug : I have to duplicate all my "\\" in \<command> otherwise these are skipped
- bug ? : it is not possible to run a Windows 10 app with \<command> (it opens explorer.exe)
- Remark : Still in \<command>, quotes are indispensable to manage paths with spaces
- Remark : it not easy for the user to find the right window title, sometimes even in task manager it is not the right title. On window 10 the right title is displayed in the tooltip which appear on mouse over in the taskbar (power user will use something like [AU3_Spy.exe](https://stackoverflow.com/questions/45552452/what-is-au3-spy-exe-where-can-i-find-it)). This detail could be documented  :  
![image](https://user-images.githubusercontent.com/7110113/149704896-3a25f24b-7416-4a0a-baf7-630047467aeb.png)


Working example of use of the beta with onenote : 
`[{FocusOrLaunch,* ‎- OneNote for Windows 10,,"C:\\Users\\username\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\OneNote for Windows 10.lnk"}]`

**Comment by schmurtzm** [comment] 2022-01-17 22:57
Just figured out that there is a bug on Focus and FocusOrLaunch on Windows 10 : you can't retrieve the focus on the window if it is minimized (the behavior is different on older versions of Windows, so there was no problem).
This is the same bug I encountered on my autoIT script above and I've adopted [this solution](https://www.autohotkey.com/boards/viewtopic.php?t=43997)  (it seems that Windows creates a second hwnd for apps when you minimize it)

Do you want a dedicated issue for this one or is it OK here ?

**Comment by guilryder** [comment] 2022-01-18 05:40
> Little bug : I have to duplicate all my "\\" in <command> otherwise these are skipped

This is intended and [documented](https://gryder.org/software/clavier-plus/documentation#text-special-chars). The same applies to `[[...]]`. Clavier+ has escaping limitations/quirks/bugs that I'm working on fixing (for instance escaping commas is sometimes not possible, and escaping sometimes requires two `\` instead of just one), but simple cases such as `\\` in commands should work fine.

> bug ? : it is not possible to run a Windows 10 app with \<command\> (it opens explorer.exe)

Works for me (with proper escaping).

> Still in \<command\>, quotes are indispensable to manage paths with spaces

As expected. Quotes are necessary to disambiguate.

> it not easy for the user to find the right window title

It depends a lot on your version of Windows, how it's configured, and the specific windows.  Many solutions out there and many caveats, I won't risk myself to make any recommendation.

> you can't retrieve the focus on the window if it is minimized (the behavior is different on older versions of Windows, so there was no problem)

Interesting regression, thanks for noticing! That's easy to fix, the latest beta should behave correctly.

**Comment by schmurtzm** [comment] 2022-01-18 21:46
> This is intended and [documented](https://gryder.org/software/clavier-plus/documentation#text-special-chars). The same applies to `[[...]]`. Clavier+ has escaping limitations/quirks/bugs that I'm working on fixing (for instance escaping commas is sometimes not possible, and escaping sometimes requires two `\` instead of just one), but simple cases such as `\\` in commands should work fine.

woops, I miss this part of the documentation ;)
> 
> > bug ? : it is not possible to run a Windows 10 app with <command> (it opens explorer.exe)
>
> Works for me (with proper escaping).

OK I got it , example for Onenote : 
`[{FocusOrLaunch,* ‎- OneNote for Windows 10,,"explorer.exe" "shell:appsFolder\\Microsoft.Office.OneNote_8wekyb3d8bbwe!microsoft.onenoteim"}]`

> It depends a lot on your version of Windows, how it's configured, and the specific windows. Many solutions out there and many caveats, I won't risk myself to make any recommendation.
> 

You're probably right... and may some users will take a look inside issues 😅 
> > you can't retrieve the focus on the window if it is minimized (the behavior is different on older versions of Windows, so there was no problem)
> 
> Interesting regression, thanks for noticing! That's easy to fix, the latest beta should behave correctly.

I've just tested the last beta, it seems already solved, thank you !

It seems it's almost done for this one 😉  I like so much using it !

**Comment by guilryder** [comment] 2022-01-23 05:27
I found no new bugs and updated the beta version with 2 tweaks:
* Reordered the arguments of `[{FocusOrLaunch}]` to make the delay entirely optional and self-document that Clavier+ applies the delay after executing the command, contrary to `[{Focus}]`. The new syntax is: `[{FocusOrLaunch,window name,command,delay}]`
* Simplified the escaping syntax for edge cases such as `[{Focus,0,\!Warning!}]` (no longer `[{Focus,0,\\!Warning!}]`). It's technically a breaking change, but I don't think many users will be impacted, if at all.

**Comment by schmurtzm** [comment] 2022-01-24 20:59
Strangely my commands was still working before modifying it...  Anyway the new syntax is OK for me. 
It is already a daily habit to use FocusOrLaunch, I can't go back anymore 😉

**Comment by guilryder** [comment] 2022-01-30 00:09
`[{FocusOrLaunch}]` implemented in e2d7d350f3499831d549a8b2e795089988fcab13, released in version 11.2.0. #

**Closed by guilryder** 2022-01-30 00:09 UTC
Labels: enhancement
